backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Publish Date, name: pubDate, widget: datetime }
      - { label: Updated Date, name: updatedDate, widget: datetime, required: false }
      - { label: Author, name: author, widget: string, default: "Arab Tech Trends" }
      - { label: Category, name: category, widget: string, default: "Technology" }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Cover Image, name: image, widget: image, required: false }
      - { label: Draft, name: draft, widget: boolean, default: false }
      - { label: Body, name: body, widget: markdown }
